"""Local-vs-remote keystroke attribution via WH_KEYBOARD_LL.

Restores the "ping-pong" mute semantics: a remote-injected keystroke
hides local speech, and the very next physical keystroke on the
controlled machine brings speech back. No 2-second timer, no
control-mode drive messages — both of which were workarounds added
when earlier attribution attempts were thought to break NVDA's
say-all and Shift-to-pause behaviour. Subsequent investigation (see
audiomute.py) traced that breakage to the old
``WavePlayer.feed`` byte-substitution wedge, not to this hook. With
that wedge replaced by an OS-level audio-session mute, the hook is
free to do its real job again.

How attribution works
---------------------
Every keystroke the Windows kernel sees passes through our low-level
keyboard hook. The ``KBDLLHOOKSTRUCT.flags`` field has the
``LLKHF_INJECTED`` and ``LLKHF_LOWER_IL_INJECTED`` bits set whenever
the keystroke was generated by ``SendInput`` from any process —
including NVDA Remote's ``LocalMachine.sendKey``. A physical key on
the keyboard hardware has neither bit set.

* injected → ``state.mark_remote_input()``  (``remote_driving = True``)
* physical → ``state.mark_local_input()``   (``remote_driving = False``)

The audiomute listener catches each state transition and toggles the
WASAPI session mute. The result: speech on the controlled side is
inaudible while the controller is pressing keys, and a single
physical keystroke from the local user restores audible speech
immediately — same audible feedback the user would have had without
the addon, from the moment they touch the keyboard.

Performance discipline
----------------------
A WH_KEYBOARD_LL hook runs on the system input thread and gates every
keystroke system-wide. Anything slow in the hook procedure makes
typing feel laggy in every application. We do the absolute minimum:

* one ``ctypes.cast`` to read the hook struct
* one bitwise-and on the flags
* one ``wx.CallAfter`` to enqueue the state change on the main thread

Then we return through ``CallNextHookEx`` immediately. The wx queue
absorbs the state update on the main thread, where the listeners
(notably audiomute) actually run.
"""
from __future__ import annotations

import ctypes
from ctypes import POINTER, c_int, c_long, wintypes

import wx

from . import logger
from . import state as state_module

log = logger.get()


# Win32 constants
WH_KEYBOARD_LL = 13
WM_KEYDOWN = 0x0100
WM_SYSKEYDOWN = 0x0104
LLKHF_INJECTED = 0x00000010
LLKHF_LOWER_IL_INJECTED = 0x00000002
HC_ACTION = 0


class KBDLLHOOKSTRUCT(ctypes.Structure):
    _fields_ = [
        ("vkCode", wintypes.DWORD),
        ("scanCode", wintypes.DWORD),
        ("flags", wintypes.DWORD),
        ("time", wintypes.DWORD),
        ("dwExtraInfo", ctypes.c_void_p),
    ]


LowLevelKeyboardProc = ctypes.WINFUNCTYPE(
    c_long, c_int, wintypes.WPARAM, wintypes.LPARAM
)

_user32 = ctypes.WinDLL("user32", use_last_error=True)
_kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)

_user32.SetWindowsHookExW.argtypes = [c_int, LowLevelKeyboardProc, wintypes.HINSTANCE, wintypes.DWORD]
_user32.SetWindowsHookExW.restype = wintypes.HHOOK
_user32.UnhookWindowsHookEx.argtypes = [wintypes.HHOOK]
_user32.UnhookWindowsHookEx.restype = wintypes.BOOL
_user32.CallNextHookEx.argtypes = [wintypes.HHOOK, c_int, wintypes.WPARAM, wintypes.LPARAM]
_user32.CallNextHookEx.restype = c_long
_kernel32.GetModuleHandleW.argtypes = [wintypes.LPCWSTR]
_kernel32.GetModuleHandleW.restype = wintypes.HMODULE


_hook_handle: int | None = None
_hook_proc_ref: object | None = None  # keep the WINFUNCTYPE alive


def _hook_proc(nCode, wParam, lParam):
    # MUST NOT raise. A raised exception from a low-level hook proc
    # drops keystrokes system-wide.
    #
    # Short-circuit when no controller has armed muting on this machine:
    # the ping-pong attribution is meaningless when ``muted_by_remote``
    # is False (``should_drop_speech`` can never be True regardless of
    # ``remote_driving``), and skipping the wx.CallAfter on every system
    # keystroke removes any conceivable per-key overhead from this
    # add-on outside of an active muted session. Direct attribute read
    # without acquiring state._lock — a Python boolean read is atomic
    # and a stale read is bounded harm (we either skip a keystroke that
    # would have been a no-op anyway, or fire mark_*_input one keystroke
    # too late).
    if nCode == HC_ACTION and wParam in (WM_KEYDOWN, WM_SYSKEYDOWN):
        if state_module.state.muted_by_remote:
            try:
                kb = ctypes.cast(lParam, POINTER(KBDLLHOOKSTRUCT))[0]
                is_injected = bool(kb.flags & (LLKHF_INJECTED | LLKHF_LOWER_IL_INJECTED))
                if is_injected:
                    wx.CallAfter(state_module.state.mark_remote_input)
                else:
                    wx.CallAfter(state_module.state.mark_local_input)
            except Exception:
                pass
    return _user32.CallNextHookEx(_hook_handle or 0, nCode, wParam, lParam)


def install() -> None:
    global _hook_handle, _hook_proc_ref
    if _hook_handle is not None:
        return
    _hook_proc_ref = LowLevelKeyboardProc(_hook_proc)
    hMod = _kernel32.GetModuleHandleW(None)
    handle = _user32.SetWindowsHookExW(WH_KEYBOARD_LL, _hook_proc_ref, hMod, 0)
    if not handle:
        err = ctypes.get_last_error()
        log.error("rsc: SetWindowsHookEx(WH_KEYBOARD_LL) failed (GetLastError=%d)", err)
        _hook_proc_ref = None
        return
    _hook_handle = handle
    log.info("rsc: WH_KEYBOARD_LL hook installed for ping-pong attribution")


def uninstall() -> None:
    global _hook_handle, _hook_proc_ref
    if _hook_handle is None:
        return
    try:
        _user32.UnhookWindowsHookEx(_hook_handle)
    except Exception:
        log.exception("rsc: UnhookWindowsHookEx failed")
    _hook_handle = None
    _hook_proc_ref = None
    log.info("rsc: WH_KEYBOARD_LL hook removed")
